### ISSUE TITLE
Support: Second Factor (U2F)  

### ISSUE THREAD

**Issue by ib54003** [brantje/passman#105]
It would be cool if you could add Two-factor authentication like Fido to unlock the passwords with a Yubikey.
https://fidoalliance.org/specifications

**Comment by brantje** [comment]
Yubikey is used to login somewhere, not for decrypting stuff ( Yea well, some stuff will be decrypted when you use Yubi).
More over, @animalillo and i thought that Yubi key can repleace passman, since the logins with Yubi are already secure.

And if i want to integrate Yubi key to passman, we need an 3rd party to talk with, not gonna happen soon. Sorry
