### ISSUE TITLE
Advanced vaults

### ISSUE THREAD

**Issue by brantje** [brantje/passman#121]
Ideas for advanced vaults here

**Comment by tiker** [comment]
For my needs, keep as is.  :)

My first Idea for everyone else:
Create some sort of Vault Manager.
- The application presents to the user a "Create New Vault" interface
- "Create New Vault" asks for 2 values - "Vault Name" and "Password" (encryption key)
- In a database table, store the vault name and something encrypted with the encryption key provided (vault name encrypted, hash of the name encrypted, etc.)
- All new password entries are encrypted with the new password
- May also want to check against other "saved vaults" to ensure the same password is not used in another vault configuration for the user (to prevent confusions over the same password entries showing in multiple vaults)

When opening PassMan or using a "Switch Password Vaults" option:
- User selects the vault (show a list of vaults the user created)
- User enters the vault password
- application uses the entered password to decrypt the encrypted value set when creating to validate if the password is correct or not
- prompt the user saying "invalid password" or show them their passwords if the password is correct


I personally do not like the idea of a vault manager even though it would make it easier for some people.  It provides a list of vaults showing the possible number of different passwords in use to unauthorized people.

Perhaps adding a configuration option "Use Vault Manager" as well.
- Add an admin level application setting that allows it to be used or not for everyone
- If the admin allows it, allow each user to (clear and) disable the vault manager allowing Passman to function the way it functions today.

**Comment by brantje** [comment]
What do you think of this? I still have to create an add button and such
![image](https://cloud.githubusercontent.com/assets/2758767/8325853/dab79cdc-1a5c-11e5-82c2-437e8edc244b.png)

**Comment by tiker** [comment]
Something like that.  Would a frame like have a maximum vault count or would it scroll if the number of vaults exceed the space?

**Comment by brantje** [comment]
It will scroll. An other option, could be a select dropdown,  not pretty but might be an option.

**Comment by tiker** [comment]
Which ever..  the window shown above would probably be more "user friendly" showing the "Last accessed" date and other things you might think of in the future.

The main idea is showing the users a list of vaults and telling them when their password is wrong rather than a blank screen and leaving them think the application messed up.

**Comment by brmiller** [comment]
Honestly, users aren't going to have hundreds of vaults in the typical case.  Scrolling after 3 to keep the modal small would be more friendly than a select dropdown.  Question: Have there been any thoughts to keeping the design responsive?  Passman is usable on a mobile device (could be better), but the design of this vault modal could have implications if it was too big.  (Modals on mobile are kinda awful to start with.)

**Comment by tiker** [comment]
I'm one of those people who will have a hundred vaults.  I'm hoping there will be a method to switch vaults the same as it is today without the "vault manager" once it is implemented.

Three vaults on the screen and scrolling for more would be fine.  I wouldn't expect the common user to have more than one single vault.

**Comment by sbrandexed** [comment]
I have some better idea's for the new 'login' window.
It will not be a dialog, just a complete page where you can select the vault.

**Comment by tiker** [comment]
But with an option to hit "cancel" and use the different vaults the way we can today without the stored (advertised) index of vaults right?  :)

**Comment by animalillo** [comment]
I think that showing the vaults on login will loose all the vault provided safety.

**Comment by animalillo** [comment]
hmmm
I have an idea about the system and keeping it secure, and improving bandwith usage in the process.
Instead of doing like now; download all, check for items that match password.
New protocol i've thinked:
  - A table with vaults containing some cyphered data in a field, and a vault-id in another.
  - A table with session data.
On the "login" process:
1 Server generates a session for the user in which it links the vault-id with random identifiers
2 Server generates an array with the the random identifiers and their corresponding cypherdata plus some extra random generated cyphered data and invalid IDs (that should be stored in the session, I think).
3 This list is sent to the client, who inserts the password as always, in a trial-error game it finds it's vault session-id and request to the server it's vault contents. 
      - If it's an invalid password: display "Creating a new vault" and on new password insert link the vault to the user.
4 Normal operation?

**Comment by animalillo** [comment]
On new vault
Confirm password, please

**Comment by brantje** [comment]
Fixed [in the NexCloud repo](https://github.com/nextcloud/passman)
